# Generated by Django 6.0.4 on 2026-04-22 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('image', models.ImageField(height_field='image_height', upload_to='uploads', width_field='image_width')),
                ('image_width', models.IntegerField(editable=False, null=True)),
                ('image_height', models.IntegerField(editable=False, null=True)),
                ('paint_type', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('avatar_width', models.IntegerField(editable=False, null=True)),
                ('avatar_height', models.IntegerField(editable=False, null=True)),
                ('avatar', models.ImageField(height_field='avatar_height', upload_to='uploads', width_field='avatar_width')),
                ('cart', models.ManyToManyField(blank=True, related_name='profiles', to='art_shop_online_app.artproduct')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveBigIntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('products', models.ManyToManyField(related_name='receipts', to='art_shop_online_app.artproduct')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='art_shop_online_app.profile')),
            ],
        ),
    ]
