# Generated by Django 6.0.4 on 2026-04-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop_online_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
