# Generated by Django 6.0.4 on 2026-04-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop_online_app', '0002_artproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='rate',
            field=models.PositiveBigIntegerField(db_default=0, default=0),
        ),
    ]
