# Generated by Django 6.0.4 on 2026-04-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop_online_app', '0003_artproduct_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artproduct',
            name='image_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artproduct',
            name='image_width',
            field=models.IntegerField(null=True),
        ),
    ]
