# Generated by Django 6.0.4 on 2026-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop_online_app', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artproduct',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
