# Generated by Django 6.0.4 on 2026-04-29 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop_online_app', '0006_artproduct_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_shop_online_app.artproduct')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_shop_online_app.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'product'), name='unique_product_per_profile_cart')],
            },
        ),
    ]
