# Generated by Django 6.0.4 on 2026-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop_online_app', '0007_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
