# Generated by Django 6.0.4 on 2026-04-30 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_shop_online_app', '0010_remove_receipt_products_receipt_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='art_shop_online_app.order'),
        ),
    ]
